version: '3.8'

services:
  php-app:
    build: ./docker/app
    container_name: php-app
    restart: always
    volumes:
      - ./src:/var/www/html
    environment:
      - APP_ENV=production
    networks:
      - app-network

  apache:
    build: ./docker/web
    container_name: apache
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php-app
    networks:
      - app-network

  monitoring:
    build: ./docker/monitoring
    container_name: monitoring
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
